# Generated by Django 5.0.4 on 2024-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_alter_source_options_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='The source name.', max_length=200),
        ),
    ]
