# Generated by Django 5.0.4 on 2024-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mei_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
