# Generated by Django 5.0.4 on 2024-07-24 13:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_item_mei_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['country', 'location', 'bib_id']},
        ),
        migrations.RemoveConstraint(
            model_name='genre',
            name='genre_name_case_insensitive_unique',
        ),
        migrations.AddField(
            model_name='source',
            name='century',
            field=models.CharField(default=None, help_text='The source century.', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.CharField(default=None, help_text='The source location (country).', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='notation',
            field=models.CharField(default='', help_text='The source notation type (for musical notation only).', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.CharField(default='', help_text='Additional notes on the source.', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='bib_id',
            field=models.CharField(help_text='The source identifier.', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='location',
            field=models.CharField(help_text='The source location (institution).', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='The source name.', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_insensitive_unique'),
        ),
    ]
