# Generated by Django 5.0.4 on 2024-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_alter_source_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='century',
            field=models.CharField(help_text='The source century.', max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='The source name.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='notation',
            field=models.CharField(help_text='The source notation type (for musical notation only).', max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.CharField(help_text='Additional notes on the source.', max_length=1024, null=True, unique=True),
        ),
    ]
