# Generated by Django 5.0.4 on 2024-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_alter_source_century_alter_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='century',
            field=models.CharField(help_text='The source century.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.CharField(help_text='The source location (country).', max_length=256),
        ),
        migrations.AlterField(
            model_name='source',
            name='location',
            field=models.CharField(help_text='The source location (institution).', max_length=256),
        ),
        migrations.AlterField(
            model_name='source',
            name='notation',
            field=models.CharField(help_text='The source notation type (for musical notation only).', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.CharField(help_text='Additional notes on the source.', max_length=1024, null=True),
        ),
    ]
