# Generated by Django 5.0.4 on 2024-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_alter_source_century_alter_source_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='century',
            field=models.CharField(blank=True, default='', help_text='The source century.', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, default='', help_text='The source name.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='notation',
            field=models.CharField(blank=True, default='', help_text='The source notation type (for musical notation only).', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Additional notes on the source.', max_length=1024),
            preserve_default=False,
        ),
    ]
