# Generated by Django 5.0.4 on 2024-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_alter_source_century_alter_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url_link',
            field=models.CharField(blank=True, help_text='External url to access the source images.', max_length=512),
        ),
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes on the source.'),
        ),
    ]
