# Generated by Django 5.0.4 on 2024-07-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0009_source_url_link_alter_source_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url_link',
            new_name='url',
        ),
    ]
