# Generated by Django 4.2.15 on 2024-08-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0010_rename_url_link_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
    ]
