# Generated by Django 4.2.15 on 2024-08-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0011_alter_genre_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MET', 'Metrical poetry'), ('RHY', 'Rhythmical poetry'), ('PRO', 'Prose')], max_length=3)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='TextTypeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_unit', models.CharField(choices=[('', 'Unspecified'), ('HEX', 'Hexameter'), ('PEN', 'Pentameter'), ('SEP', 'Septenarius'), ('TRI', 'Trimeter')], default='', max_length=3)),
                ('type_of_meter', models.CharField(choices=[('', 'Unspecified'), ('IAM', 'Iamb'), ('TRO', 'Trochee'), ('SPO', 'Spondee'), ('ANA', 'Anapest'), ('DAK', 'Daktyl')], default='', max_length=3)),
                ('strophic', models.CharField(choices=[('', 'Not strophic'), ('ISO', 'Isometric'), ('HET', 'Heterometric')], default='', max_length=3)),
                ('refrain', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='MusicForm',
            new_name='MusicalForm',
        ),
        migrations.RemoveField(
            model_name='abstractitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='music_form',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text_form',
        ),
        migrations.AlterField(
            model_name='abstractitem',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='browse.genre'),
        ),
        migrations.RemoveField(
            model_name='abstractitem',
            name='theme',
        ),
        migrations.DeleteModel(
            name='TextForm',
        ),
        migrations.AddField(
            model_name='texttypespecification',
            name='abstract_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.abstractitem'),
        ),
        migrations.AddField(
            model_name='texttypespecification',
            name='text_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.texttype'),
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='text_type',
            field=models.ManyToManyField(through='browse.TextTypeSpecification', to='browse.texttype'),
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='theme',
            field=models.ManyToManyField(to='browse.theme'),
        ),
    ]
