# Generated by Django 4.2.15 on 2024-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0013_alter_texttype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttypespecification',
            name='strophic',
            field=models.CharField(blank=True, choices=[('', 'Not strophic'), ('ISO', 'Isometric'), ('HET', 'Heterometric')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='texttypespecification',
            name='type_of_meter',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('IAM', 'Iamb'), ('TRO', 'Trochee'), ('SPO', 'Spondee'), ('ANA', 'Anapest'), ('DAK', 'Daktyl')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='texttypespecification',
            name='verse_unit',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('HEX', 'Hexameter'), ('PEN', 'Pentameter'), ('SEP', 'Septenarius'), ('TRI', 'Trimeter')], default='', max_length=3, null=True),
        ),
    ]
