# Generated by Django 4.2.15 on 2024-09-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0014_alter_texttypespecification_strophic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mei_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
    ]
