# Generated by Django 4.2.15 on 2024-09-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0015_remove_item_mei_file_remove_item_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='nick_name',
        ),
    ]
