# Generated by Django 4.2.15 on 2024-09-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0016_rename_name_source_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location_end',
            new_name='foliation_end',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='location_start',
            new_name='foliation_start',
        ),
    ]
