# Generated by Django 4.2.15 on 2024-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0017_rename_location_end_item_foliation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='concordances',
            field=models.TextField(blank=True, help_text='Concordances with the Codex Buranus.'),
        ),
    ]
