# Generated by Django 5.1.7 on 2025-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0018_source_concordances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('description', models.CharField(help_text='Description of the glyph.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tei_file',
            field=models.CharField(help_text="TEI Filename (without '.tei' extension).", max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='language',
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ManyToManyField(to='browse.language'),
        ),
    ]
