FONT_ID_TO_DESCRIPTION = {
	"1": "Punctum",
	"2": "Tractulus",
	"3": "Stropha",
	"4": "Distropha",
	"5": "Tristropha",
	"6": "Virga",
	"7": "Virga liquescent",
	"8": "Special virga (?)",
	"9": "Virga strata",
	"10": "Pressus maior",
	"11": "Pressus maior + stropha",
	"12": "Virga + oriscus + punctum (separated form) (?)",
	"13": "Virga strata + 2 subpuncta",
	"14": "Virga strata + 2 subpuncta + stropha",
	"15": "Virga liquescent + 1 subpunctum",
	"16": "Virga liquescent + 2 subpuncta",
	"17": "Virga + 1 subpunctum + substropha",
	"18": "Virga + 3 subpuncta",
	"19": "Virga + 2 subpuncta + substropha",
	"20": "Virga + 3 subpuncta + stropha",
	"21": "Virga + 4 subpuncta",
	"22": "Virga + 3 subpuncta + epiphonus (?)",
	"23": "Virga + 3 subpuncta + substropha",
	"24": "Virga + 5 subpuncta",
	"25": "Virga with stroke",
	"26": "Virga liquescent with stroke",
	"27": "Virga + 2 subpuncta + substropha + stropha",
	"28": "Epiphonus",
	"29": "Epiphonus + 1 prepunctum",
	"30": "Pes",
	"31": "Pes liquescent",
	"32": "Pes + 2 subpuncta",
	"33": "Pes + 1 subpunctum + substropha",
	"34": "Pes + 2 subpuncta + stropha",
	"35": "Pes + 3 subpuncta",
	"36": "Pes + 2 subpuncta + substropha",
	"37": "Pes + 3 subpuncta + substropha",
	"38": "Pes + 3 subpuncta + stropha",
	"39": "Pes + 2 subpuncta + substropha + stropha",
	"40": "Pes + 1 prepunctum",
	"41": "Pes liquescent + 1 prepunctum",
	"42": "Pes + porrectus",
	"43": "Pes + pressus minor",
	"44": "ancus",
	"45": "Clivis",
	"46": "Clivis liquescent",
	"47": "Clivis episemata (?)",
	"48": "Clivis with stroke",
	"49": "Clivis + stropha",
	"50": "Clivis + 2 prepuncta",
	"51": "Clivis + 2 subpuncta",
	"52": "Clivis + 2 subpuncta + stropha",
	"53": "Torculus",
	"54": "Torculus + oriscus",
	"55": "Torculus + pressus minor",
	"56": "Porrectus",
	"57": "Porrectus liquescent",
	"58": "Quilisma 2 loops",
	"59": "Quilisma 2 loops liquescent",
	"60": "Quilisma 2 loops + clivis",
	"61": "Quilisma 2 loops + clivis + 1 subpunctum",
	"62": "Quilisma 2 loops + clivis + 2 subpuncta",
	"63": "Quilisma 2 loops + 1 prepunctum + clivis + 1 subpunctum + stropha",
	"64": "Quilisma 2 loops + 1 prepunctum + clivis",
	"65": "Quilisma 2 loops + clivis + stropha",
	"66": "Quilisma 2 loops + 1 prepunctum + clivis + stropha",
	"67": "Quilisma 2 loops + porrectus",
	"68": "Quilisma 2 loops + 1 prepunctum + clivis + oriscus",
	"69": "Quilisma 2 loops + oriscus",
	"70": "Quilisma 2 loops + pressus maior",
	"71": "Quilisma 2 loops + oriscus liquescent",
	"72": "Quilisma 2 loops + oriscus liquescent + 1 subpunctum",
	"73": "Quilisma 2 loops + oriscus liquescent + 1 prepunctum + 1 substropha",
	"74": "Quilisma 2 loops + 1 prepunctum",
	"75": "Quilisma 2 loops + 2 subpuncta",
	"76": "Quilisma 2 loops + 1 prepunctum + 2 subpuncta",
	"77": "Quilisma 2 loops + 1 subpunctum + substropha",
	"78": "Quilisma 2 loops + 1 prepunctum + 1 subpunctum + substropha",
	"79": "Quilisma 2 loops + 2 subpuncta + stropha",
	"80": "Quilisma 2 loops + 1 prepunctum + 2 subpuncta + stropha",
	"81": "Quilisma 2 loops + 3 subpuncta",
	"82": "Quilisma 2 loops + 2 subpuncta + substropha",
	"83": "Quilisma 2 loops + 1 prepunctum + 2 subpuncta + substropha",
	"84": "Quilisma 2 loops + 3 subpuncta + substropha",
	"85": "Quilisma 2 loops + ancus + 2 subpuncta",
	"86": "Quilisma 3 loops",
	"87": "Quilisma 3 loops liquescent",
	"88": "Quilisma 3 loops + ancus",
	"89": "Quilisma 3 loops + clivis",
	"90": "Quilisma 3 loops + clivis liquescent",
	"91": "Quilisma 3 loops + 1 prepunctum + clivis",
	"92": "Quilisma 3 loops + 1 prepunctum + clivis + 2 subpuncta",
	"93": "Quilisma 3 loops + clivis + oriscus",
	"94": "Quilisma 3 loops + clivis + 1 subpunctum",
	"95": "Quilisma 3 loops + clivis + stropha",
	"96": "Quilisma 3 loops + 1 prepunctum + clivis + stropha",
	"97": "Quilisma 3 loops + porrectus",
	"98": "Quilisma 3 loops + 1 prepunctum + porrectus",
	"99": "Quilisma 3 loops + oriscus",
	"100": "Quilisma 3 loops + oriscus liquescent",
	"101": "Quilisma 3 loops + pressus maior",
	"102": "Quilisma 3 loops + oriscus liquescent + 1 subpunctum",
	"103": "Quilisma 3 loops + 2 subpuncta",
	"104": "Quilisma 3 loops + 1 prepunctum + 2 subpuncta",
	"105": "Quilisma 3 loops + 1 subpunctum + substropha",
	"106": "Quilisma 3 loops + 3 subpuncta",
	"107": "Quilisma 3 loops + 2 subpuncta + substropha",
	"108": "Quilisma 3 loops + 1 prepunctum + 2 subpuncta + substropha",
	"109": "Quilisma 3 loops + 2 subpuncta + stropha",
	"110": "Quilisma 3 loops + 1 prepunctum + 2 subpuncta + stropha",
	"111": "Quilisma 3 loops + 1 prepunctum + 2 subpuncta + substropha",
	"112": "Quilisma 3 loops + 1 prepunctum",
	"113": "Quilisma 4 loops",
	"114": "Quilisma 4 loops + 3 subpuncta",
	"115": "Climacus",
	"116": "Climacus with stroke",
	"117": "Climacus + epiphonus (?)",
	"118": "Climacus + stropha",
	"119": "Climacus + stropha + pressus minor",
	"120": "Climacus + 2 prepuncta",
	"121": "Climacus + 2 prepuncta + stropha",
	"122": "Scandicus",
	"123": "Scandicus liquescent",
	"124": "Scandicus with tractulus as middle note",
	"125": "Scandicus with tractulus as middle note + quilisma 3 loops",
}