FONT_ID_TO_DESCRIPTION = {
	"1": "Punctum",
	"2": "Tractulus",
	"3": "Stropha",
	"4": "Distropha",
	"5": "Tristropha",
	"6": "Virga",
	"7": "Virga liq.",
	"8": "Special virga (?)",
	"9": "Virga + oriscus",
	"10": "Virga + oriscus + 1 subpunctum",
	"11": "Virga + oriscus + 1 subpunctum + stropha",
	"12": "Virga + oriscus + 2 subpuncta",
	"13": "Virga + oriscus + 2 subpuncta + stropha",
	"14": "Virga liq. + 1 subpunctum",
	"15": "Virga liq. + 2 subpuncta",
	"16": "Virga + 1 subpunctum + substropha",
	"17": "Virga + 3 subpuncta",
	"18": "Virga + 2 subpuncta + substropha",
	"19": "Virga + 3 subpuncta + stropha",
	"20": "Virga + 4 subpuncta",
	"21": "Virga + 3 subpuncta + epiphonus",
	"22": "Virga + 3 subpuncta + substropha",
	"23": "Virga + 5 subpuncta",
	"24": "Virga with stroke",
	"25": "Virga liq. with stroke",
	"26": "Virga + 2 subpuncta + substropha + stropha",
	"27": "Epiphonus",
	"28": "1 prepunctum + epiphonus",
	"29": "Pes",
	"30": "Pes liq.",
	"31": "Pes + 2 subpuncta",
	"32": "Pes + 1 subpunctum + substropha",
	"33": "Pes + 2 subpuncta + stropha",
	"34": "Pes + 3 subpuncta",
	"35": "Pes + 2 subpuncta + substropha",
	"36": "Pes + 3 subpuncta + substropha",
	"37": "Pes + 3 subpuncta + stropha",
	"38": "Pes + 2 subpuncta + substropha + stropha",
	"39": "1 prepunctum + pes",
	"40": "1 prepunctum + pes liq.",
	"41": "Torculus resupinus",
	"42": "Pes + oriscus",
	"43": "Pes + oriscus + 1 subpunctum",
	"44": "Ancus",
	"45": "Clivis",
	"46": "Clivis liq.",
	"47": "Clivis with stroke above",
	"48": "Clivis with stroke",
	"49": "Clivis + stropha",
	"50": "2 prepuncta + clivis",
	"51": "Clivis + 2 subpuncta",
	"52": "Clivis + 2 subpuncta + stropha",
	"53": "Torculus",
	"54": "Torculus + 1 subpunctum",
	"55": "Torculus + oriscus",
	"56": "Torculus + oriscus + 1 subpunctum",
	"57": "Porrectus",
	"58": "Porrectus liq.",
	"59": "Porrectus + oriscus + 1 subpunctum",
	"60": "Quilisma 2 loops + virga",
	"61": "Quilisma 2 loops + virga liq.",
	"62": "Quilisma 2 loops + clivis",
	"63": "Quilisma 2 loops + clivis + 1 subpunctum",
	"64": "Quilisma 2 loops + clivis + 2 subpuncta",
	"65": "1 prepunctum + quilisma 2 loops + clivis + 1 subpunctum + stropha",
	"66": "1 prepunctum + quilisma 2 loops + clivis",
	"67": "Quilisma 2 loops + clivis + stropha",
	"68": "1 prepunctum + quilisma 2 loops + clivis + stropha",
	"69": "Quilisma 2 loops + porrectus",
	"70": "1 prepunctum + quilisma 2 loops + clivis liq.",
	"71": "Quilisma 2 loops + virga + oriscus",
	"72": "Quilisma 2 loops + virga + oriscus + 1 subpunctum",
	"73": "Quilisma 2 loops + virga + oriscus liq.",
	"74": "Quilisma 2 loops + virga + oriscus liq. + 1 subpunctum",
	"75": "1 prepunctum + quilisma 2 loops + virga + oriscus liq. + 1 substropha",
	"76": "1 prepunctum + quilisma 2 loops + virga",
	"77": "Quilisma 2 loops + virga + 2 subpuncta",
	"78": "1 prepunctum + quilisma 2 loops + virga + 2 subpuncta",
	"79": "Quilisma 2 loops + virga + 1 subpunctum + substropha",
	"80": "1 prepunctum + quilisma 2 loops + virga + 1 subpunctum + substropha",
	"81": "Quilisma 2 loops + virga + 2 subpuncta + stropha",
	"82": "1 prepunctum + quilisma 2 loops + virga + 2 subpuncta + stropha",
	"83": "Quilisma 2 loops + virga + 3 subpuncta",
	"84": "Quilisma 2 loops + virga + 2 subpuncta + substropha",
	"85": "1 prepunctum + quilisma 2 loops + virga + 2 subpuncta + substropha",
	"86": "Quilisma 2 loops + virga + 3 subpuncta + substropha",
	"87": "Quilisma 2 loops + ancus + 2 subpuncta",
	"88": "Quilisma 3 loops + virga",
	"89": "Quilisma 3 loops + virga liq.",
	"90": "Quilisma 3 loops + ancus",
	"91": "Quilisma 3 loops + clivis",
	"92": "Quilisma 3 loops + clivis liq.",
	"93": "1 prepunctum + quilisma 3 loops + clivis",
	"94": "1 prepunctum + quilisma 3 loops + clivis + 2 subpuncta",
	"95": "Quilisma 3 loops + clivis + oriscus",
	"96": "Quilisma 3 loops + clivis + 1 subpunctum",
	"97": "Quilisma 3 loops + clivis + stropha",
	"98": "1 prepunctum + quilisma 3 loops + clivis + stropha",
	"99": "Quilisma 3 loops + porrectus",
	"100": "1 prepunctum + quilisma 3 loops + porrectus",
	"101": "Quilisma 3 loops + virga + oriscus",
	"102": "Quilisma 3 loops + virga + oriscus liq.",
	"103": "Quilisma 3 loops + virga + oriscus + 1 subpunctum",
	"104": "Quilisma 3 loops + virga + oriscus liq. + 1 subpunctum",
	"105": "Quilisma 3 loops + virga + 2 subpuncta",
	"106": "1 prepunctum + quilisma 3 loops + virga + 2 subpuncta",
	"107": "Quilisma 3 loops + virga + 1 subpunctum + substropha",
	"108": "Quilisma 3 loops + virga + 3 subpuncta",
	"109": "Quilisma 3 loops + virga + 2 subpuncta + substropha",
	"110": "1 prepunctum + quilisma 3 loops + virga + 2 subpuncta + substropha",
	"111": "Quilisma 3 loops + virga + 2 subpuncta + stropha",
	"112": "1 prepunctum + quilisma 3 loops + virga + 2 subpuncta + stropha",
	"113": "1 prepunctum + Quilisma 3 loops + virga + 2 subpuncta + substropha",
	"114": "1 prepunctum + Quilisma 3 loops + virga",
	"115": "Quilisma 4 loops + virga",
	"116": "Quilisma 4 loops + virga + 3 subpuncta",
	"117": "Virga + 2 subpuncta",
	"118": "Virga with stroke + 2 subpuncta<",
	"119": "Virga + 2 subpuncta + epiphonus",
	"120": "Virga + 2 subpuncta + stropha",
	"121": "Virga + 2 subpuncta + stropha + oriscus + 1subpunctum",
	"122": "2 prepuncta + virga + 2 subpuncta",
	"123": "2 prepuncta + virga + 2 subpuncta + stropha",
	"124": "2 prepuncta + virga",
	"125": "2 prepuncta + virga liq.",
	"126": "1 prepunctum + tractulus + virga",
	"127": "1 prepunctum + tractulus + quilisma 3 loops + virga",
}